import numpy as np
from typing import List, Optional
from logging import getLogger
from numpy.random import Generator

from styne.mcmc.metropolishastings import MetropolisHastings
from styne.mcmc.factory import MHFactory
from styne.mcmc.acceptance import AcceptanceProbability
from styne.mcmc.proposal import (
    ProposalMethod, PartitionedSurrogateProposal
)
from styne.mcmc.transition import TransitionData
from styne.mcmc.localised import (
    LocalisedSurrogateDensity,
    LocalisedSurrogateTransitionMeasure
)
from styne.mcmc.method.mrw import MRWFactory
from styne.statistics.covariance import IIDCovarianceMatrix
from styne.mcmc.method.pcn import PCNFactory, PCNProposal
from styne.mcmc.method.mala import MALAFactory
from styne.mcmc.method.pmala import PMALAFactory
from styne.mcmc.diagnostics import (
    ChainDiagnostics, DummyDiagnostics, AcceptanceRateDiagnostics
)
from styne.mcmc.method.ratio import RatioEstimator
from styne.mcmc.acceptance import StandardAcceptance
from styne.statistics.interface import DensityInterface
from styne.statistics.measure import AbsolutelyContinuousProbabilityMeasure
from styne.parameter.parameter import Parameter
from styne.parameter.vector import Vector
from styne.utility.partition import Partition, IndependentPartitionDensity
import styne.utility.tuning as tuning


class LocalisedSurrogateTransition(ProposalMethod):
    """Proposal generated by a localised surrogate chain."""

    def __init__(
        self,
        surrogateMeasure: LocalisedSurrogateTransitionMeasure,
        burnin: int,
        thinning: int,
        correction: Optional[RatioEstimator] = None,
    ):
        if not isinstance(surrogateMeasure,
                          LocalisedSurrogateTransitionMeasure):
            raise TypeError(
                "surrogateMeasure must be a "
                "LocalisedSurrogateTransitionMeasure instance."
            )

        self._surrogateMeasure = surrogateMeasure
        self._burnin = burnin
        self._thinning = thinning

        if correction is None:
            self._correction = RatioEstimator(
                surrogateMeasure, burnin, thinning, 'cumulant'
            )
        else:
            self._correction = correction

    @property
    def density(self) -> LocalisedSurrogateDensity:
        """Target density of the surrogate chain."""
        return self._surrogateMeasure.density

    @property
    def measure(self) -> LocalisedSurrogateTransitionMeasure:
        return self._surrogateMeasure

    @property
    def correction(self) -> RatioEstimator:
        return self._correction

    def propose(self, state: Parameter, rng):
        self._surrogateMeasure.location = state

        coarseProposal, nextRng = self._surrogateMeasure.sample(
            rng
        )
        return TransitionData(state, coarseProposal), nextRng

    def log_acceptance_correction(self, state, proposal):
        density = self._surrogateMeasure.density
        logDiffSurrogate = (density.evaluate_log_surrogate(proposal)
                            - density.evaluate_log_surrogate(state))
        logRatioEstimate = self._correction.log_ratio_estimate(state, proposal)
        return -logDiffSurrogate - logRatioEstimate


class DART(MetropolisHastings):
    """Metropolis-Hastings chain driven by a localised surrogate.

    Parameters
    ----------
    target : DensityInterface
        Fine-level target density.
    surrogateMeasure : LocalisedSurrogateTransitionMeasure
        Localised surrogate transition measure (required positionally for
        compatibility with inner intermediate chains).
    diagnostics : ChainDiagnostics
    burnin : int
    thinning : int
    correction : RatioEstimator, optional
        Only consumed when proposal is None.
    acceptance : AcceptanceProbability, optional
    proposal : ProposalMethod, optional
    """

    def __init__(
        self,
        target: DensityInterface,
        surrogateMeasure: LocalisedSurrogateTransitionMeasure,
        diagnostics: ChainDiagnostics,
        burnin: int = 5,
        thinning: int = 1,
        correction: Optional[RatioEstimator] = None,
        acceptance: Optional[AcceptanceProbability] = None,
        proposal: Optional[ProposalMethod] = None,
        rng: Optional[Generator] = None,
    ):
        if not isinstance(surrogateMeasure,
                          LocalisedSurrogateTransitionMeasure):
            raise TypeError(
                "surrogateMeasure must be a "
                "LocalisedSurrogateTransitionMeasure instance."
            )

        if proposal is None:
            proposal = LocalisedSurrogateTransition(
                surrogateMeasure, burnin, thinning, correction
            )

        super().__init__(target, proposal, diagnostics,
                         acceptance=acceptance, rng=rng)

    def _log_mh_ratio(self, transition: TransitionData):
        """MH ratio with generic acceptance correction."""
        logDiffTarget = (
            transition.proposed.logDensity - transition.current.logDensity
        )
        correction = self._proposalMethod.log_acceptance_correction(
            transition.state, transition.proposal)
        return logDiffTarget + correction


class DARTFactory(MHFactory):
    """Factory for constructing DART chains.

    Required configuration before 'create()', set via the matching setters,
    'surrogate' (list of surrogate densities, coarsest first), 'regularisation'
    (one gamma per level), and 'nChain' (one subchain length per level). The
    three lists must be equal length. 'create()' raises if any is unset or the
    lengths disagree.

    When a partition and fine prior are set, the root chain operates on
    the coarse subspace only; fine modes are proposed from the prior.
    Without partition, all behaviour is identical to the original.

    Configure the selected root chain through ``root``. The proposal parameter
    is ``root.proposalCovariance`` for ``"mrw"``, ``root.beta`` for ``"pcn"``
    and ``"pmala"``, and ``root.stepSize`` for ``"mala"``. If it is not set,
    DART tunes the corresponding parameter automatically during ``create()``.
    """

    def __init__(self, root: str = "pcn"):
        super().__init__()

        if root == "mrw":
            self._rootFactory = MRWFactory()
        elif root == "pcn":
            self._rootFactory = PCNFactory()
        elif root == "mala":
            self._rootFactory = MALAFactory()
        elif root == "pmala":
            self._rootFactory = PMALAFactory()
        else:
            raise ValueError(f"Invalid root chain: {root}.")

        self._surrogate = None
        self._gammaList = None
        self._thetaList = None
        self._nChain = None
        self._burnin = 5
        self._thinning = 1
        self._crankUpSteps = 0
        self._crankUpProposalVariance = None
        self._crankUpInitialState = None
        self._crankedState = None
        self._correction = None
        self._correctionType = None
        self._acceptance = None
        self._partition: Optional[Partition] = None
        self._finePrior: Optional[AbsolutelyContinuousProbabilityMeasure] = None
        self._finePCNStep = 1.0
        self._spectralWeights = None
        self._localisedDensity = None

        self._surrogateDensity = None
        self._nSurrogate = None
        self._logger = getLogger(__name__)
        self._subDiagnostics = DummyDiagnostics

    @property
    def root(self) -> MHFactory:
        return self._rootFactory

    @root.setter
    def root(self, factory: MHFactory):
        self._rootFactory = factory

    @property
    def surrogate(self) -> List[DensityInterface]:
        return self._surrogate

    @surrogate.setter
    def surrogate(self, modelList: List[DensityInterface]):
        self._surrogate = modelList

    @property
    def regularisation(self) -> List[float]:
        return self._gammaList

    @regularisation.setter
    def regularisation(self, gammaValues: List[float]):
        self._gammaList = gammaValues

    @property
    def tempering(self) -> List[float]:
        return self._thetaList

    @tempering.setter
    def tempering(self, thetaValues: List[float]):
        self._thetaList = thetaValues

    @property
    def nChain(self) -> List[int]:
        return self._nChain

    @nChain.setter
    def nChain(self, nValues: List[int]):
        self._nChain = nValues

    @property
    def burnin(self) -> int:
        return self._burnin

    @burnin.setter
    def burnin(self, value: int):
        if not isinstance(value, int) or value < 0:
            raise ValueError(
                f"burnin must be a non-negative integer. Got {value}.")
        self._burnin = value

    @property
    def thinning(self) -> int:
        return self._thinning

    @thinning.setter
    def thinning(self, value: int):
        if not isinstance(value, int) or value < 1:
            raise ValueError(
                f"thinning must be a positive integer. Got {value}.")
        self._thinning = value

    @property
    def acceptance(self) -> AcceptanceProbability:
        return self._acceptance

    @acceptance.setter
    def acceptance(self, strategy: AcceptanceProbability):
        if not isinstance(strategy, AcceptanceProbability):
            raise TypeError(
                "acceptance must be an AcceptanceProbability instance.")
        self._acceptance = strategy

    @property
    def correction(self) -> RatioEstimator:
        return self._correction

    @correction.setter
    def correction(self, strategy: RatioEstimator):
        if not isinstance(strategy, RatioEstimator):
            raise TypeError("correction must be a RatioEstimator instance.")
        self._correction = strategy

    @property
    def correctionType(self) -> Optional[str]:
        return self._correctionType

    @correctionType.setter
    def correctionType(self, value: str):
        if value not in ('is', 'bridge', 'cumulant'):
            raise ValueError(
                f"correctionType must be 'is', 'bridge', or 'cumulant', got '{value}'.")
        self._correctionType = value

    @property
    def crankUpSteps(self) -> int:
        return self._crankUpSteps

    @crankUpSteps.setter
    def crankUpSteps(self, steps: int):
        if not isinstance(steps, int) or steps < 0:
            raise ValueError(
                f"crankUpSteps must be a non-negative integer. Got {steps}.")
        self._crankUpSteps = steps

    @property
    def spectralWeights(self):
        return self._spectralWeights

    @spectralWeights.setter
    def spectralWeights(self, value):
        self._spectralWeights = value

    @property
    def localisedDensity(self):
        """The innermost LocalisedSurrogateDensity, available after create()."""
        return self._localisedDensity

    @property
    def crankUpInitialState(self) -> Optional[Parameter]:
        return self._crankUpInitialState

    @crankUpInitialState.setter
    def crankUpInitialState(self, value: Optional[Parameter]):
        self._crankUpInitialState = value

    @property
    def crankedState(self) -> Optional[Parameter]:
        return self._crankedState

    @property
    def crankUpProposalVariance(self) -> Optional[float]:
        return self._crankUpProposalVariance

    @crankUpProposalVariance.setter
    def crankUpProposalVariance(self, value: float):
        if value is not None and value <= 0:
            raise ValueError("crankUpProposalVariance must be positive.")
        self._crankUpProposalVariance = value

    @property
    def partition(self) -> Optional[Partition]:
        return self._partition

    @partition.setter
    def partition(self, value: Partition):
        self._partition = value

    @property
    def finePrior(
        self,
    ) -> Optional[AbsolutelyContinuousProbabilityMeasure]:
        return self._finePrior

    @finePrior.setter
    def finePrior(self, value: AbsolutelyContinuousProbabilityMeasure):
        self._finePrior = value

    @property
    def subDiagnostics(self):
        return self._subDiagnostics

    @subDiagnostics.setter
    def subDiagnostics(self, factory):
        if not callable(factory):
            raise TypeError("subDiagnostics must be a zero-argument callable returning a ChainDiagnostics.")
        self._subDiagnostics = factory

    @property
    def finePCNStep(self) -> float:
        """pCN step size on fine block. Requires Gaussian fine prior."""
        return self._finePCNStep

    @finePCNStep.setter
    def finePCNStep(self, value: float):
        self._finePCNStep = value

    def _validate(self) -> None:
        super()._validate()

        requiredParams = {
            "surrogate": self._surrogate,
            "regularisation": self._gammaList,
            "nChain": self._nChain
        }
        missingParams = [
            key for key, value in requiredParams.items() if value is None]
        if missingParams:
            raise ValueError(
                f"Missing parameters: {', '.join(missingParams)}")

        if not isinstance(self._surrogate, list) or not all(
                isinstance(m, DensityInterface) for m in self._surrogate):
            raise TypeError(
                "surrogate must be a list of DensityInterface instances.")

        if not isinstance(
                self._gammaList, list) or not all(
                np.isscalar(x) for x in self._gammaList):
            raise TypeError("regularisation must be a list of scalars.")

        if not isinstance(
                self._nChain, list) or not all(
                isinstance(n, int) for n in self._nChain):
            raise TypeError("nChain must be a list of integers.")

        listLengths = [
            len(self._surrogate),
            len(self._gammaList),
            len(self._nChain)]
        if len(set(listLengths)) != 1:
            raise ValueError(
                f"Inconsistent parameter lengths: {listLengths}")

        self._nSurrogate = listLengths[0]

        if self._nSurrogate < 1:
            raise ValueError("At least one surrogate level is required.")

        if np.any(np.array(self._gammaList) <= 0.0):
            raise ValueError(
                "All regularisation parameters must be positive.")

        if any(n < 0 for n in self._nChain):
            raise ValueError(
                "All nChain values must be non-negative integers.")

        if any(n == 0 for n in self._nChain):
            self._logger.warning(
                "At least one subchain length is zero. This recovers "
                "standard Metropolis-Hastings at that level."
            )

        partitionSet = self._partition is not None
        finePriorSet = self._finePrior is not None
        if partitionSet != finePriorSet:
            raise ValueError(
                "partition and finePrior must both be set or both be None.")

        if partitionSet:
            if not (0.0 < self._finePCNStep <= 1.0):
                raise ValueError(
                    f"finePCNStep must satisfy 0 < beta <= 1. Got {self._finePCNStep}."
                )
            coarseDim = self._partition.rule.component_dimension(0)
            surrDim = self._surrogate[0].domainDimension
            if coarseDim != surrDim:
                raise ValueError(
                    f"Coarse partition dimension ({coarseDim}) does not "
                    f"match surrogate[0] dimension ({surrDim}).")

    def _build_surrogate_densities(self) -> None:
        if self._thetaList is None:
            self._surrogateDensity = [
                LocalisedSurrogateDensity(
                    regularisation=g, tempering=1.0,
                    surrogateDensity=m,
                    spectralWeights=self._spectralWeights)
                for g, m in zip(self._gammaList, self._surrogate)
            ]
        else:
            if len(self._thetaList) != self._nSurrogate:
                raise ValueError(
                    "Inconsistent number of tempering parameters")

            if np.any(
                    np.array(self._thetaList) <= 0.0) or np.any(
                    np.array(self._thetaList) > 1.0):
                raise ValueError(
                    "Invalid tempering parameter value detected. "
                    "Require 0 < theta <= 1.")

            self._surrogateDensity = [
                LocalisedSurrogateDensity(
                    regularisation=g, tempering=t,
                    surrogateDensity=m,
                    spectralWeights=self._spectralWeights)
                for g, t, m in zip(
                    self._gammaList, self._thetaList,
                    self._surrogate)
            ]

    def _root_needs_tuning(self) -> bool:
        if isinstance(self._rootFactory, MRWFactory):
            return self._rootFactory.proposalCovariance is None
        if isinstance(self._rootFactory, PCNFactory):
            return self._rootFactory.beta is None
        if isinstance(self._rootFactory, MALAFactory):
            return self._rootFactory.stepSize is None
        if isinstance(self._rootFactory, PMALAFactory):
            return self._rootFactory.beta is None
        return False

    def _tune_root(self, surr0, initialState) -> None:
        """Auto-tune root chain proposal parameter against surr0."""
        self._rootFactory.target = surr0

        if isinstance(self._rootFactory, MRWFactory):
            tuning.MRWTuner(self._rootFactory, initialState).tune()
        elif isinstance(self._rootFactory, PCNFactory):
            tuning.PCNTuner(self._rootFactory, initialState).tune()
        elif isinstance(self._rootFactory, MALAFactory):
            tuning.MALATuner(self._rootFactory, initialState).tune()
        elif isinstance(self._rootFactory, PMALAFactory):
            tuning.PMALATuner(self._rootFactory, initialState).tune()

    def _crank_up_target(self) -> DensityInterface:
        """Full-dimensional crank-up target.

        Without partition: the coarsest surrogate density directly.
        With partition: joins coarse surrogate and fine prior so the
        crank-up MRW explores the full parameter space.
        """
        if self._partition is None:
            return self._surrogate[0]

        return IndependentPartitionDensity(
            self._partition,
            [self._surrogate[0], self._finePrior.density],
        )

    def _create_sampler(self) -> DART:
        self._build_surrogate_densities()
        self._localisedDensity = self._surrogateDensity[0]

        if self._crankUpSteps > 0:
            crankUpTarget = self._crank_up_target()
            dim = crankUpTarget.domainDimension
            init = self.crankUpInitialState if self.crankUpInitialState is not None else tuning.infer_init(crankUpTarget)

            crankUpFactory = MRWFactory()
            crankUpFactory.target = crankUpTarget
            crankUpFactory.rng = self.rng
            crankUpFactory.diagnostics = AcceptanceRateDiagnostics()

            if self._crankUpProposalVariance is None:
                config = tuning.RWTunerConfig(acceptanceGoal=0.5, tolerance=0.2)
                crankUpSampler = tuning.MRWTuner(crankUpFactory, init, config=config).tune()
            else:
                crankUpFactory.proposalCovariance = IIDCovarianceMatrix(dim, self._crankUpProposalVariance)
                crankUpSampler = crankUpFactory.create()
            
            crankUpSampler.storeChain = False
            self._logger.info("crank-up on coarse surrogate, %d steps", self._crankUpSteps)
            crankUpSampler.run(self._crankUpSteps, init)
            self._crankedState = crankUpSampler.lastState
        else:
            self._crankedState = self.crankUpInitialState if self.crankUpInitialState is not None else tuning.infer_init(self._crank_up_target())

        self._rootFactory.rng = self.rng

        if self._root_needs_tuning():
            if self._partition is not None:
                rootInit = Vector(self._partition.rule.extract(0, self._crankedState.coordinate))
            else:
                rootInit = self._crankedState
            self._tune_root(self._localisedDensity, rootInit)

        self._rootFactory.target = self._localisedDensity
        self._rootFactory.diagnostics = self._subDiagnostics()
        rootMcmc = self._rootFactory.create()

        surrogateMeasure = LocalisedSurrogateTransitionMeasure(
            rootMcmc, self._nChain[0])

        for levelIndex in range(1, self._nSurrogate):
            surrogateMcmc = DART(
                self._surrogateDensity[levelIndex],
                surrogateMeasure,
                self._subDiagnostics(),
                self._burnin,
                self._thinning,
                rng=self.rng
            )
            surrogateMeasure = LocalisedSurrogateTransitionMeasure(
                surrogateMcmc, self._nChain[levelIndex])

        correction = (
            self._correction if self._correction is not None
            else RatioEstimator(
                surrogateMeasure, self._burnin, self._thinning,
                self._correctionType or 'cumulant')
        )

        if self._partition is not None:
            coarseProposal = LocalisedSurrogateTransition(
                surrogateMeasure, self._burnin, self._thinning, correction)
            fineKernel = PCNProposal(self._finePrior, self._finePCNStep)
            proposal = PartitionedSurrogateProposal(
                self._partition, coarseProposal, fineKernel, self._finePrior)
        else:
            proposal = None

        mainChain = DART(
            self._target,
            surrogateMeasure,
            self._diagnostics,
            self._burnin,
            self._thinning,
            correction,
            self._acceptance,
            proposal=proposal,
            rng=self.rng
        )

        return mainChain
