from typing import List, Optional
from logging import getLogger
from numpy.random import Generator

from styne.mcmc.metropolishastings import MetropolisHastings
from styne.mcmc.acceptance import AcceptanceProbability
from styne.mcmc.proposal import ProposalMethod, PartitionedProposalMixin
from styne.mcmc.surrogate import SurrogateTransitionMeasure
from styne.mcmc.diagnostics import ChainDiagnostics
from styne.mcmc.factory import MHFactory
from styne.mcmc.method.mrw import MRWFactory
from styne.mcmc.method.pcn import PCNFactory
from styne.mcmc.method.mala import MALAFactory
from styne.mcmc.method.pmala import PMALAFactory
from styne.mcmc.diagnostics import DummyDiagnostics, AcceptanceRateDiagnostics
from styne.mcmc.transition import TransitionData
from styne.statistics.interface import DensityInterface
from styne.statistics.measure import AbsolutelyContinuousProbabilityMeasure
from styne.statistics.dirac import DiracMeasure
from styne.parameter.parameter import Parameter
from styne.parameter.vector import Vector
from styne.utility.partition import Partition, IndependentPartitionDensity
from styne.utility.densityarithmetic import LogScalingWrapper
from styne.statistics.radonnikodym import RadonNikodym
from styne.statistics.covariance import IIDCovarianceMatrix
import styne.utility.tuning as tuning


class MLDAProposal(PartitionedProposalMixin, ProposalMethod):
    """Proposal generated by running a surrogate MCMC chain.

    When a partition and fine prior are provided, the surrogate chain
    operates only on the coarse component; fine modes are drawn
    independently from the prior and merged to form the full proposal.
    Without a partition, the surrogate chain runs in the full space
    (original behaviour).

    Parameters
    ----------
    surrogateMeasure : SurrogateTransitionMeasure
        Wraps the surrogate MCMC chain and its run length.
    partition : Partition, optional
        Coarse/fine split of the full parameter.
    finePrior : AbsolutelyContinuousProbabilityMeasure, optional
        Prior over the fine components; used for independent draws.
    """

    def __init__(
        self,
        surrogateMeasure: SurrogateTransitionMeasure,
        partition: Optional[Partition] = None,
        finePrior: Optional[AbsolutelyContinuousProbabilityMeasure] = None,
    ):
        self._init_partition(partition, finePrior)
        self._surrogateMeasure = surrogateMeasure

    def propose(self, state: Parameter, rng):
        if self.isPartitioned:
            initialState = self._coarse_from(state)
        else:
            initialState = state

        coarseProposal, nextRng = self._surrogateMeasure.transition(
            initialState, rng
        )
        if not self.isPartitioned:
            return TransitionData(state, coarseProposal), nextRng
        fineProposal, nextRng = self._pFinePrior.sample(nextRng)
        fullProposal = self._merge(
            coarseProposal.coordinate, fineProposal.coordinate, state)
        return TransitionData(state, fullProposal), nextRng

    @property
    def density(self) -> DensityInterface:
        """Target density of the surrogate chain."""
        return self._surrogateMeasure.density

    @property
    def measure(self) -> SurrogateTransitionMeasure:
        return self._surrogateMeasure


class MultilevelDelayedAcceptanceMCMC(MetropolisHastings):
    """Multilevel Delayed Acceptance MCMC.

    When a partition and fine prior are provided, only the coarse
    surrogate density enters the MH correction; the fine-prior terms
    cancel exactly from the acceptance ratio.

    Parameters
    ----------
    target : DensityInterface
        Fine-level target density (full space).
    surrogateMeasure : SurrogateTransitionMeasure
        Surrogate chain wrapped as a probability measure.
    diagnostics : ChainDiagnostics
        Tracks transition statistics.
    partition : Partition, optional
        Coarse/fine split of the full parameter.
    finePrior : AbsolutelyContinuousProbabilityMeasure, optional
        Prior over the fine components.
    """

    def __init__(
        self,
        target: DensityInterface,
        surrogateMeasure: SurrogateTransitionMeasure,
        diagnostics: ChainDiagnostics,
        acceptance: AcceptanceProbability = None,
        partition: Optional[Partition] = None,
        finePrior: Optional[AbsolutelyContinuousProbabilityMeasure] = None,
        rng: Optional[Generator] = None,
    ):
        self._partition = partition
        self._finePrior = finePrior

        proposalMethod = MLDAProposal(surrogateMeasure, partition, finePrior)
        super().__init__(target, proposalMethod, diagnostics,
                         acceptance=acceptance, rng=rng)

    def _log_mh_ratio(self, transition: TransitionData):
        """Delayed-acceptance MH ratio, with optional fine-prior correction.

        Without partition: logDiffTarget - logDiffSurrogate.
        With partition:    logDiffTarget - logDiffFinePrior
                           - logDiffCoarseSurrogate.

        The fine-prior terms cancel from the target exactly, making the
        correction exact rather than approximate.
        """
        state = transition.state
        proposal = transition.proposal

        logDiffTarget = (
            transition.proposed.logDensity - transition.current.logDensity
        )

        surr = self._proposalMethod.density

        if self._partition is None:
            logDiffSurr = (
                surr.evaluate_log(proposal) - surr.evaluate_log(state)
            )
            return logDiffTarget - logDiffSurr

        rule = self._partition.rule
        stateC = Vector(rule.extract(0, state.coordinate))
        proposalC = Vector(rule.extract(0, proposal.coordinate))
        stateF = Vector(rule.extract(1, state.coordinate))
        proposalF = Vector(rule.extract(1, proposal.coordinate))

        logDiffSurr = (
            surr.evaluate_log(proposalC) - surr.evaluate_log(stateC)
        )
        logDiffFinePrior = (
            self._finePrior.density.evaluate_log(proposalF)
            - self._finePrior.density.evaluate_log(stateF)
        )
        return logDiffTarget - logDiffFinePrior - logDiffSurr


class MLDAFactory(MHFactory):
    """Factory for constructing multilevel delayed acceptance chains.

    Builds a hierarchy of surrogate chains, with the coarsest level
    driven by a configurable root sampler (MRW, pCN, or MALA).

    When a partition and fine prior are set, the outermost chain
    uses a partition-aware proposal and MH ratio so that the surrogate
    chain operates on the coarse subspace only.

    Parameters
    ----------
    root : str, optional
        Root chain type: 'mrw' (default), 'pcn', or 'mala'.
    """

    def __init__(self, root="mrw"):

        if root == "mrw":
            self._rootFactory = MRWFactory()
        elif root == "pcn":
            self._rootFactory = PCNFactory()
        elif root == "mala":
            self._rootFactory = MALAFactory()
        elif root == "pmala":
            self._rootFactory = PMALAFactory()
        else:
            raise ValueError(f"Invalid root chain: {root}")

        super().__init__()

        self._surrogate = None
        self._nChain = None
        self._crankUpSteps = 0
        self._crankUpProposalVariance = None
        self._crankUpInitialState = None
        self._crankedState = None
        self._acceptance: AcceptanceProbability = None
        self._partition: Optional[Partition] = None
        self._finePrior: Optional[AbsolutelyContinuousProbabilityMeasure] = None
        self._thetaList = None

        self._nSurr = None
        self._logger = getLogger(__name__)
        self._subDiagnostics = DummyDiagnostics

    @property
    def surrogate(self) -> List[DensityInterface]:
        return self._surrogate

    @surrogate.setter
    def surrogate(self, densityList):
        self._surrogate = densityList

    @property
    def nChain(self) -> List[int]:
        return self._nChain

    @nChain.setter
    def nChain(self, n):
        self._nChain = n

    @property
    def tempering(self) -> Optional[List[float]]:
        return self._thetaList

    @tempering.setter
    def tempering(self, thetaValues: Optional[List[float]]):
        self._thetaList = thetaValues

    @property
    def root(self) -> MHFactory:
        return self._rootFactory

    @property
    def acceptance(self) -> AcceptanceProbability:
        return self._acceptance

    @acceptance.setter
    def acceptance(self, strategy: AcceptanceProbability):
        self._acceptance = strategy

    @property
    def partition(self) -> Optional[Partition]:
        return self._partition

    @partition.setter
    def partition(self, value: Partition):
        self._partition = value

    @property
    def finePrior(
        self,
    ) -> Optional[AbsolutelyContinuousProbabilityMeasure]:
        return self._finePrior

    @finePrior.setter
    def finePrior(self, value: AbsolutelyContinuousProbabilityMeasure):
        self._finePrior = value

    @property
    def subDiagnostics(self):
        return self._subDiagnostics

    @subDiagnostics.setter
    def subDiagnostics(self, factory):
        if not callable(factory):
            raise TypeError("subDiagnostics must be a zero-argument callable returning a ChainDiagnostics.")
        self._subDiagnostics = factory

    @property
    def crankUpSteps(self) -> int:
        return self._crankUpSteps

    @crankUpSteps.setter
    def crankUpSteps(self, steps: int):
        if not isinstance(steps, int) or steps < 0:
            raise ValueError(
                f"crankUpSteps must be a non-negative integer. Got {steps}.")
        self._crankUpSteps = steps

    @property
    def crankUpProposalVariance(self) -> Optional[float]:
        return self._crankUpProposalVariance

    @crankUpProposalVariance.setter
    def crankUpProposalVariance(self, value: float):
        if value is not None and value <= 0:
            raise ValueError("crankUpProposalVariance must be positive.")
        self._crankUpProposalVariance = value

    @property
    def crankUpInitialState(self) -> Optional[Parameter]:
        return self._crankUpInitialState

    @crankUpInitialState.setter
    def crankUpInitialState(self, value: Optional[Parameter]):
        self._crankUpInitialState = value

    @property
    def crankedState(self) -> Optional[Parameter]:
        return self._crankedState

    def _validate(self) -> None:
        super()._validate()

        required = {
            "surrogate": self._surrogate,
            "nChain": self._nChain
        }
        missing = [k for k, v in required.items() if v is None]
        if missing:
            raise ValueError(f"Missing parameters: {', '.join(missing)}")

        if not isinstance(self._surrogate, list) or not all(
            isinstance(m, DensityInterface) for m in self._surrogate
        ):
            raise TypeError(
                "surrogate must be a list of DensityInterface instances.")

        if not isinstance(self._nChain, list) or not all(
            isinstance(n, int) for n in self._nChain
        ):
            raise TypeError("nChain must be a list of integers.")

        lengths = [len(self._surrogate), len(self._nChain)]
        if len(set(lengths)) != 1:
            raise ValueError(f"Inconsistent parameter lengths: {lengths}")

        self._nSurr = lengths[0]

        if self._nSurr < 1:
            raise ValueError("At least one surrogate level is required.")

        if self._thetaList is not None:
            if not isinstance(self._thetaList, list) or not all(
                isinstance(theta, (int, float)) and not isinstance(theta, bool)
                for theta in self._thetaList
            ):
                raise TypeError("tempering must be a list of floats.")

            if len(self._thetaList) != self._nSurr:
                raise ValueError(
                    f"Inconsistent parameter lengths: "
                    f"{[self._nSurr, len(self._thetaList)]}"
                )

            if any(theta <= 0.0 or theta > 1.0 for theta in self._thetaList):
                raise ValueError("All tempering parameters must be in (0, 1].")

            from styne.statistics.radonnikodym import RadonNikodym
            for theta, surr in zip(self._thetaList, self._surrogate):
                if theta < 1.0 and not isinstance(surr, RadonNikodym):
                    raise TypeError(
                        "Tempering < 1.0 is only supported when the surrogate "
                        "density is an instance of RadonNikodym."
                    )

        if any(n <= 0 for n in self._nChain):
            raise ValueError("All subchain lengths must be positive integers.")

        partitionSet = self._partition is not None
        finePriorSet = self._finePrior is not None
        if partitionSet != finePriorSet:
            raise ValueError(
                "partition and finePrior must both be set or both be None.")

        if partitionSet:
            coarseDim = self._partition.rule.component_dimension(0)
            surrDim = self._surrogate[0].domainDimension
            if coarseDim != surrDim:
                raise ValueError(
                    f"Coarse partition dimension ({coarseDim}) does not match "
                    f"surrogate[0] dimension ({surrDim}).")

    def _root_needs_tuning(self) -> bool:
        if isinstance(self._rootFactory, MRWFactory):
            return self._rootFactory.proposalCovariance is None
        if isinstance(self._rootFactory, PCNFactory):
            return self._rootFactory.beta is None
        if isinstance(self._rootFactory, MALAFactory):
            return self._rootFactory.stepSize is None
        if isinstance(self._rootFactory, PMALAFactory):
            return self._rootFactory.beta is None
        return False

    def _tune_root(self, surr0, initialState) -> None:
        """Auto-tune root chain proposal parameter against surr0."""
        self._rootFactory.target = surr0

        if isinstance(self._rootFactory, MRWFactory):
            tuning.MRWTuner(self._rootFactory, initialState).tune()
        elif isinstance(self._rootFactory, PCNFactory):
            tuning.PCNTuner(self._rootFactory, initialState).tune()
        elif isinstance(self._rootFactory, MALAFactory):
            tuning.MALATuner(self._rootFactory, initialState).tune()
        elif isinstance(self._rootFactory, PMALAFactory):
            tuning.PMALATuner(self._rootFactory, initialState).tune()

    def _crank_up_target(
        self, surrogate0: Optional[DensityInterface] = None
    ) -> DensityInterface:
        """Full-dimensional crank-up target.

        Without partition: the coarsest surrogate density directly.
        With partition: joins coarse surrogate and fine prior into a
        full-dimensional joint density so the crank-up MRW explores
        the full space.
        """
        coarseSurrogate = (
            surrogate0 if surrogate0 is not None else self._surrogate[0]
        )
        if self._partition is None:
            return coarseSurrogate

        return IndependentPartitionDensity(
            self._partition,
            [coarseSurrogate, self._finePrior.density],
        )

    def _create_sampler(self):
        surrogates = list(self._surrogate)
        if self._thetaList is not None:
            for lvl in range(self._nSurr):
                theta = self._thetaList[lvl]
                if theta < 1.0:
                    surr = surrogates[lvl]
                    scaled_derivative = LogScalingWrapper(
                        surr.derivative, theta
                    )
                    surrogates[lvl] = RadonNikodym(
                        surr.reference, scaled_derivative
                    )

        if self._crankUpSteps > 0:
            crankUpTarget = self._crank_up_target(surrogates[0])
            dim = crankUpTarget.domainDimension
            init = self.crankUpInitialState if self.crankUpInitialState is not None else tuning.infer_init(crankUpTarget)

            crankUpFactory = MRWFactory()
            crankUpFactory.target = crankUpTarget
            crankUpFactory.rng = self.rng
            crankUpFactory.diagnostics = AcceptanceRateDiagnostics()

            if self._crankUpProposalVariance is None:
                config = tuning.RWTunerConfig(acceptanceGoal=0.5, tolerance=0.2)
                crankUpSampler = tuning.MRWTuner(crankUpFactory, init, config=config).tune()
            else:
                crankUpFactory.proposalCovariance = IIDCovarianceMatrix(dim, self._crankUpProposalVariance)
                crankUpSampler = crankUpFactory.create()
            
            crankUpSampler.storeChain = False
            self._logger.info("crank-up on coarse surrogate, %d steps", self._crankUpSteps)
            crankUpSampler.run(self._crankUpSteps, init)
            self._crankedState = crankUpSampler.lastState
        else:
            self._crankedState = self.crankUpInitialState if self.crankUpInitialState is not None else tuning.infer_init(self._crank_up_target(surrogates[0]))

        self._rootFactory.rng = self.rng

        if self._root_needs_tuning():
            if self._partition is not None:
                rootInit = Vector(self._partition.rule.extract(0, self._crankedState.coordinate))
            else:
                rootInit = self._crankedState
            self._tune_root(surrogates[0], rootInit)

        self._rootFactory.target = surrogates[0]
        self._rootFactory.diagnostics = self._subDiagnostics()
        surrogateChain = self._rootFactory.create()

        surrogateMeasure = SurrogateTransitionMeasure(
            surrogateChain, self._nChain[0], DiracMeasure()
        )

        for lvl in range(1, self._nSurr):
            surrogateChain = MultilevelDelayedAcceptanceMCMC(
                surrogates[lvl],
                surrogateMeasure,
                self._subDiagnostics(),
                rng=self.rng
            )
            surrogateMeasure = SurrogateTransitionMeasure(
                surrogateChain, self._nChain[lvl], DiracMeasure()
            )

        mainChain = MultilevelDelayedAcceptanceMCMC(
            self._target,
            surrogateMeasure,
            self._diagnostics,
            self._acceptance,
            self._partition,
            self._finePrior,
            rng=self.rng
        )

        return mainChain
