from typing import Optional
from styne.statistics.interface import DensityInterface
from styne.statistics.measure import (
    ProbabilityMeasure,
    AbsolutelyContinuousProbabilityMeasure,
)
from styne.statistics.dirac import DiracMeasure
from styne.parameter.parameter import Parameter
from styne.mcmc.metropolishastings import MetropolisHastings


class SurrogateTransitionMeasure(AbsolutelyContinuousProbabilityMeasure):
    """
    Probability measure, implicitly defined through a Markov chain.

    A realisation is generated by running a short surrogate chain from
    an initial measure and returning the final state.

    Parameters
    ----------
    initialMeasure : ProbabilityMeasure
        Provides the initial state for each surrogate chain run.
        Deterministic initial chains are recovered via DiracMeasure
    surrogateMCMC : MetropolisHastings
        The Sampler defining this measure.
    nChain : int
        Number of transitions in each surrogate chain run.
    """

    def __init__(
            self,
            surrogateMCMC: MetropolisHastings,
            nChain: int,
            initialMeasure: Optional[ProbabilityMeasure] = None,
    ):
        if not isinstance(nChain, int) or nChain < 0:
            raise ValueError(
                f"nChain must be a non-negative integer. Got {nChain}.")

        self._initialMeasure = (
            initialMeasure if initialMeasure is not None else DiracMeasure()
        )
        self._mcmc = surrogateMCMC
        self._nChain = nChain

    @property
    def mcmc(self):
        return self._mcmc

    @property
    def chain(self):
        return self._mcmc.chain

    @property
    def subchainLength(self) -> int:
        return self._nChain

    @property
    def density(self) -> DensityInterface:
        """Target density of the surrogate chain."""
        return self._mcmc.target

    @property
    def initialMeasure(self) -> ProbabilityMeasure:
        return self._initialMeasure

    def transition(self, initialState: Parameter, randomState):
        """Run the surrogate transition from an explicit initial state.

        This is the numerical path used by delayed-acceptance proposals. It
        does not populate the wrapped sampler's chain or alter its runner
        state, so one surrogate measure can safely be reused by independent
        outer transitions.
        """
        if not self._mcmc._uses_pure_step():
            raise RuntimeError(
                "Surrogate transitions require a sampler with step()."
            )

        state = self._mcmc.initial_state(initialState)
        for _ in range(self._nChain):
            state, _, randomState = self._mcmc.step(state, randomState)
        return self._mcmc._parameter_from_state(state), randomState

    def sample(self, randomState) -> tuple[Parameter, object]:
        """
        Generate a realisation by running the surrogate chain.

        Draws an initial state from the initial measure, runs the
        surrogate chain for 'nChain' steps, and returns the final state.

        Parameters
        ----------
        randomState : object
            Backend-native random state for both the initial draw and chain.

        Returns
        -------
        (Parameter, object)
            Final state and propagated random state.
        """
        initialState, nextState = self.initialMeasure.sample(randomState)
        return self.transition(initialState, nextState)
