import numpy as np
from typing import Optional
from styne.statistics.interface import DensityInterface
from styne.statistics.measure import (
    ProbabilityMeasure,
    AbsolutelyContinuousProbabilityMeasure,
)
from styne.statistics.dirac import DiracMeasure
from styne.parameter.parameter import Parameter
from styne.mcmc.metropolishastings import MetropolisHastings


class SurrogateTransitionMeasure(AbsolutelyContinuousProbabilityMeasure):
    """
    Probability measure, implicitly defined through a Markov chain.

    A realisation is generated by running a short surrogate chain from
    an initial measure and returning the final state.

    Parameters
    ----------
    initialMeasure : ProbabilityMeasure
        Provides the initial state for each surrogate chain run.
        Deterministic initial chains are recovered via DiracMeasure
    surrogateMCMC : MetropolisHastings
        The Sampler defining this measure.
    nChain : int
        Number of transitions in each surrogate chain run.
    """

    def __init__(self,
        surrogateMCMC: MetropolisHastings,
        nChain: int,
        initialMeasure: Optional[ProbabilityMeasure] = None
    ):
        if not isinstance(nChain, int) or nChain < 0:
            raise ValueError(
                f"nChain must be a non-negative integer. Got {nChain}.")

        self._initialMeasure = initialMeasure if initialMeasure is not None else DiracMeasure()
        self._mcmc = surrogateMCMC
        self._nChain = nChain


    @property
    def mcmc(self):
        return self._mcmc

    @property
    def chain(self):
        return self._mcmc.chain

    @property
    def subchainLength(self) -> int:
        return self._nChain

    @property
    def density(self) -> DensityInterface:
        """Target density of the surrogate chain."""
        return self._mcmc.target

    @property
    def initialMeasure(self) -> ProbabilityMeasure:
        return self._initialMeasure

    def draw(self, rng) -> Parameter:
        """
        Generate a realisation by running the surrogate chain.

        Draws an initial state from the initial measure, runs the
        surrogate chain for 'nChain' steps, and returns the final state.

        Parameters
        ----------
        rng : Generator
            NumPy random generator, used for the initial measure draw.

        Returns
        -------
        Parameter
            Final state of the surrogate chain.

        Note
        ----
        The 'rng' parameter is used to draw the initial state but
        is not propagated into the surrogate MCMC run, which uses its
        own internal RNG. Passing a seeded generator therefore does not
        make the full draw reproducible.
        """
        init = self.initialMeasure.draw(rng)
        self._mcmc.run(self._nChain, init)

        realisation = init.clone()
        realisation.coordinate = self.chain.trajectory[-1]

        return realisation
